version: '3.8'

services:

    database_crm:
        image: postgres
        container_name: database_crm
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_crm
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
      
# The existing database container configuration...
    php-apache1:
        container_name: php-apache1
        build:
            context: ./php
        ports:
            - '8080:80'
        volumes:
            - ./src:/var/www/laravel_crm
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - database_crm